name: continous-integration-david

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pruebas de SAST
        run: echo "EjecuciÃ³n de pruebas de SAST"

      - name: Crear credentials.ini
        run: |
          sed "s/\${USERNAME}/${{ secrets.USERNAME }}/g; s/\${PASSWORD}/${{ secrets.PASSWORD }}/g" credentials.ini.tpl > credentials.ini
          echo "Contenido de credentials.ini:"
          cat credentials.ini

      - name: Build docker image
        run: |
          docker build -t devops_ws:$(date +%s) .

